### PR TITLE
[Pull Request]: Added "daily" games feature in chess.com

### PR DESCRIPTION
**Pull request by tausiq2003**
You might be aware of daily games, which goes for days. So, I have added the daily feature, with the default live route, you can't analyze daily games. For that i have added daily route too. Please check and lmk.

### CODE REVIEW

**Comment by cmgchess** [comment]
Hi @tausiq2003 thanks for the PR! 
I missed daily games and didn't realize it had a different endpoint. I will have a look when I'm free. Meanwhile you can remove the console logs added. I believe they were added for testing :)

**Comment by tausiq2003** [comment]
done, thanks for the repo btw, i was looking for this, building something.

**Comment by cmgchess** [comment]
on second thought i think it would be better to separate routes for daily and live since daily doesn't use the concept of timestamps. What do you think?

**Comment by tausiq2003** [comment]
Yup, that will be good

**Comment by tausiq2003** [comment]
Btw do you have rate limiting in this api?

**Comment by cmgchess** [comment]
I haven't implemented any rate limiting myself. If you are facing such maybe vercel is doing it by themselves since I'm using a free deployment.

**Comment by cmgchess** [comment]
> ok ig you will merge it if i fix the timestamp thing, can you elaborate like how to? i mean what to do?

instead of the dynamic [gameFormat] you could create 2 separate folders for live and daily. 
so `live/game/[gameId]` and `daily/game/[gameId]`. both of them can have separate route.ts files. The rest is just the same except you don't have to accept timestamps from query params. For the `moveTimes` parameter in `getPgnFromUCI` you could pass an empty `[]`. The route doc is also easier since no timestamps needed

**Comment by tausiq2003** [comment]
check it out, if some changes needed lmk

**Comment by cmgchess** [comment]
lgtm

**Comment by tausiq2003** [comment]
please merge it then.

**Comment by cmgchess** [comment]
Thanks for the contribution @tausiq2003 :)

**Pull request merged**
